apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: sample-app
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      color: blue
  template:
    metadata:
      labels:
        app: sample-app
        color: blue
    spec:
      containers:
      - name: sample-app
        image: nginx:1.21
        volumeMounts:
        - name: custom-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: custom-html
        configMap:
          name: blue-html
