apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: sample-app
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      color: green
  template:
    metadata:
      labels:
        app: sample-app
        color: green
    spec:
      containers:
      - name: sample-app
        image: nginx:1.22
        volumeMounts:
        - name: custom-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: custom-html
        configMap:
          name: green-html
