apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
    color: blue  # Initially routes to the blue deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Use ClusterIP or NodePort depending on your cluster setup

